/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsys.ui;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import trainsys.utils.Auth;
import trainsys.utils.MsgBox;

/**
 *
 * @author ADMIN
 */
public class TrainSysJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrame
     */
    public TrainSysJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        gach1 = new javax.swing.JToolBar.Separator();
        btnTau = new javax.swing.JButton();
        btnChuyenDi = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnVeTau = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnXemLichTrinh = new javax.swing.JButton();
        btnTimChuyenTau = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        statusBar = new javax.swing.JPanel();
        lblThongtin = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        anhNen = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mni = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMK = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnQuanLy = new javax.swing.JMenu();
        mniTau = new javax.swing.JMenuItem();
        mniChuyenDi = new javax.swing.JMenuItem();
        minKhachHang = new javax.swing.JMenuItem();
        mniVeTau = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnThongKe = new javax.swing.JMenu();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnHoTro = new javax.swing.JMenu();
        mniGiaiDap = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();
        mniHuongDan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHƯƠNG TRÌNH QUẢN LÝ TÀU HỎA");

        toolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toolBar.setRollover(true);
        toolBar.setAlignmentX(1.0F);
        toolBar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N

        btnDangXuat.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        toolBar.add(btnDangXuat);
        toolBar.add(gach1);

        btnTau.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnTau.setText("Tàu");
        btnTau.setFocusable(false);
        btnTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTau.setPreferredSize(new java.awt.Dimension(55, 55));
        btnTau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnTau);

        btnChuyenDi.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnChuyenDi.setText("Chuyến đi");
        btnChuyenDi.setFocusable(false);
        btnChuyenDi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnChuyenDi);

        btnKhachHang.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnKhachHang);

        btnVeTau.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnVeTau.setText("   Vé tàu   ");
        btnVeTau.setFocusable(false);
        btnVeTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeTau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnVeTau);
        toolBar.add(jSeparator1);

        btnXemLichTrinh.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnXemLichTrinh.setText("Xem lịch trình");
        btnXemLichTrinh.setFocusable(false);
        btnXemLichTrinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXemLichTrinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnXemLichTrinh);

        btnTimChuyenTau.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnTimChuyenTau.setText("Tìm chuyến tàu");
        btnTimChuyenTau.setFocusable(false);
        btnTimChuyenTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTimChuyenTau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTimChuyenTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimChuyenTauActionPerformed(evt);
            }
        });
        toolBar.add(btnTimChuyenTau);
        toolBar.add(jSeparator2);

        btnHuongDan.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        toolBar.add(btnHuongDan);

        statusBar.setBackground(new java.awt.Color(190, 197, 197));

        lblThongtin.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        lblThongtin.setText("Chương trình quản lý tàu hỏa");
        lblThongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongtinMouseClicked(evt);
            }
        });

        lblDongHo.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        lblDongHo.setText("00:00:00 AM");

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongtin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusBarLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThongtin)
                    .addComponent(lblDongHo)))
        );

        anhNen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mni.setBackground(new java.awt.Color(214, 221, 255));
        mni.setForeground(new java.awt.Color(51, 0, 153));
        mni.setText("Hệ thống");

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setText("Đăng xuất");
        mni.add(mniDangXuat);

        mniDoiMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMK.setText("Đổi mật khẩu");
        mni.add(mniDoiMK);
        mni.add(jSeparator4);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKetThuc.setText("Kết thúc");
        mni.add(mniKetThuc);

        menuBar.add(mni);

        mnQuanLy.setBackground(new java.awt.Color(214, 221, 255));
        mnQuanLy.setForeground(new java.awt.Color(51, 0, 153));
        mnQuanLy.setText("Quản lý");

        mniTau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniTau.setText("Tàu");
        mnQuanLy.add(mniTau);

        mniChuyenDi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniChuyenDi.setText("Chuyến đi");
        mnQuanLy.add(mniChuyenDi);

        minKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        minKhachHang.setText("Khách hàng");
        mnQuanLy.add(minKhachHang);

        mniVeTau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mniVeTau.setText("Vé tàu");
        mnQuanLy.add(mniVeTau);
        mnQuanLy.add(jSeparator5);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnQuanLy.add(mniNhanVien);

        menuBar.add(mnQuanLy);

        mnThongKe.setBackground(new java.awt.Color(214, 221, 255));
        mnThongKe.setForeground(new java.awt.Color(51, 0, 153));
        mnThongKe.setText("Thống kê");

        mniDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mniDoanhThu.setText("Thống kê doanh thu");
        mnThongKe.add(mniDoanhThu);

        menuBar.add(mnThongKe);

        mnHoTro.setBackground(new java.awt.Color(214, 221, 255));
        mnHoTro.setForeground(new java.awt.Color(51, 0, 153));
        mnHoTro.setText("Hỗ trợ");

        mniGiaiDap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mniGiaiDap.setText("Giải đáp câu hỏi");
        mnHoTro.add(mniGiaiDap);
        mnHoTro.add(jSeparator6);

        mniGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniGioiThieu.setText("Giới thiệu");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnHoTro.add(mniGioiThieu);

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHuongDan.setText("Hướng dẫn sử dụng");
        mnHoTro.add(mniHuongDan);

        menuBar.add(mnHoTro);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(anhNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anhNen, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        toolBar.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblThongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtinMouseClicked
        moGioiThieu();
    }//GEN-LAST:event_lblThongtinMouseClicked

    private void btnTimChuyenTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimChuyenTauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimChuyenTauActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        this.openNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        moGioiThieu();
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuongDanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainSysJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhNen;
    private javax.swing.JButton btnChuyenDi;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnTau;
    private javax.swing.JButton btnTimChuyenTau;
    private javax.swing.JButton btnVeTau;
    private javax.swing.JButton btnXemLichTrinh;
    private javax.swing.JToolBar.Separator gach1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblThongtin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem minKhachHang;
    private javax.swing.JMenu mnHoTro;
    private javax.swing.JMenu mnQuanLy;
    private javax.swing.JMenu mnThongKe;
    private javax.swing.JMenu mni;
    private javax.swing.JMenuItem mniChuyenDi;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniGiaiDap;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniTau;
    private javax.swing.JMenuItem mniVeTau;
    private javax.swing.JPanel statusBar;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    private  void init() {
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
        this.startDongHo();
        setLocationRelativeTo(null);
    }
    void startDongHo() {
        SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
        new Timer(1000, (ActionEvent e) -> {
            lblDongHo.setText(formater.format(new Date()));
        }).start();
    }

    void openNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    private void moGioiThieu() {
        if (Auth.isLogin()) {
            new GioiThieuJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
}
