/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsys.ui;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import trainsys.utils.Auth;
import trainsys.utils.MsgBox;

/**
 *
 * @author ADMIN
 */
public class TrainSysJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrame
     */
    public TrainSysJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnTau = new javax.swing.JButton();
        btnChuyenDi = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnVeTau = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnLichTrinh = new javax.swing.JButton();
        btnChuyenTau = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        statusBar = new javax.swing.JPanel();
        lblThongtin = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        anhNen = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        mniDoiMK = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnQuanLy = new javax.swing.JMenu();
        mnuTau = new javax.swing.JMenuItem();
        mnuChuyenDi = new javax.swing.JMenuItem();
        mnuKhachHang = new javax.swing.JMenuItem();
        mnuVeTau = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuNhanVien = new javax.swing.JMenuItem();
        mnThongKe = new javax.swing.JMenu();
        mnuDonahThu = new javax.swing.JMenuItem();
        mnHoTro = new javax.swing.JMenu();
        mnuCauHoi = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuGioiThieu = new javax.swing.JMenuItem();
        mnuHuongDan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHƯƠNG TRÌNH QUẢN LÝ TÀU HỎA");
        setBackground(new java.awt.Color(255, 255, 255));

        toolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toolBar.setRollover(true);
        toolBar.setAlignmentX(1.0F);
        toolBar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N

        btnDangXuat.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\log out.png")); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        toolBar.add(btnDangXuat);
        toolBar.add(jSeparator3);

        btnTau.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnTau.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\train.png")); // NOI18N
        btnTau.setText("Tàu");
        btnTau.setFocusable(false);
        btnTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTau.setPreferredSize(new java.awt.Dimension(78, 55));
        btnTau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTauActionPerformed(evt);
            }
        });
        toolBar.add(btnTau);

        btnChuyenDi.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnChuyenDi.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\trip-train.png")); // NOI18N
        btnChuyenDi.setText("Chuyến đi");
        btnChuyenDi.setFocusable(false);
        btnChuyenDi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDi.setPreferredSize(new java.awt.Dimension(78, 55));
        btnChuyenDi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnChuyenDi);

        btnKhachHang.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnKhachHang.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\cake.png")); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setFocusable(false);
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setPreferredSize(new java.awt.Dimension(78, 55));
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        toolBar.add(btnKhachHang);

        btnVeTau.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnVeTau.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\train-ticket.png")); // NOI18N
        btnVeTau.setText("   Vé tàu   ");
        btnVeTau.setFocusable(false);
        btnVeTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVeTau.setPreferredSize(new java.awt.Dimension(78, 55));
        btnVeTau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVeTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeTauActionPerformed(evt);
            }
        });
        toolBar.add(btnVeTau);
        toolBar.add(jSeparator1);

        btnLichTrinh.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnLichTrinh.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\schedule.png")); // NOI18N
        btnLichTrinh.setText("Xem lịch trình");
        btnLichTrinh.setFocusable(false);
        btnLichTrinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLichTrinh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnLichTrinh);

        btnChuyenTau.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnChuyenTau.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\search-location.png")); // NOI18N
        btnChuyenTau.setText("Tìm chuyến tàu");
        btnChuyenTau.setFocusable(false);
        btnChuyenTau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenTau.setPreferredSize(new java.awt.Dimension(78, 55));
        btnChuyenTau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenTauActionPerformed(evt);
            }
        });
        toolBar.add(btnChuyenTau);
        toolBar.add(jSeparator2);

        btnHuongDan.setFont(new java.awt.Font("Oswald SemiBold", 0, 12)); // NOI18N
        btnHuongDan.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Globe.png")); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setPreferredSize(new java.awt.Dimension(78, 55));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnHuongDan);

        statusBar.setBackground(new java.awt.Color(190, 197, 197));

        lblThongtin.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        lblThongtin.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Info.png")); // NOI18N
        lblThongtin.setText("Chương trình quản lý tàu hỏa");
        lblThongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongtinMouseClicked(evt);
            }
        });

        lblDongHo.setFont(new java.awt.Font("Oswald", 0, 12)); // NOI18N
        lblDongHo.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Alarm.png")); // NOI18N
        lblDongHo.setText("00:00:00 AM");

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThongtin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusBarLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThongtin)
                    .addComponent(lblDongHo)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        anhNen.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Trainsys.png")); // NOI18N
        anhNen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anhNen)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anhNen, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
        );

        mnHeThong.setBackground(new java.awt.Color(214, 221, 255));
        mnHeThong.setForeground(new java.awt.Color(51, 0, 153));
        mnHeThong.setText("Hệ thống");

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\log out.png")); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnHeThong.add(mniDangXuat);

        mniDoiMK.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDoiMK.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Refresh.png")); // NOI18N
        mniDoiMK.setText("Đổi mật khẩu");
        mniDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMKActionPerformed(evt);
            }
        });
        mnHeThong.add(mniDoiMK);
        mnHeThong.add(jSeparator4);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKetThuc.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\turn-off.png")); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnHeThong.add(mniKetThuc);

        menuBar.add(mnHeThong);

        mnQuanLy.setBackground(new java.awt.Color(214, 221, 255));
        mnQuanLy.setForeground(new java.awt.Color(51, 0, 153));
        mnQuanLy.setText("Quản lý");

        mnuTau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuTau.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\train.png")); // NOI18N
        mnuTau.setText("Tàu");
        mnuTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTauActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuTau);

        mnuChuyenDi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuChuyenDi.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\trip-train.png")); // NOI18N
        mnuChuyenDi.setText("Chuyến đi");
        mnuChuyenDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChuyenDiActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuChuyenDi);

        mnuKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnuKhachHang.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\cake.png")); // NOI18N
        mnuKhachHang.setText("Khách hàng");
        mnuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKhachHangActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuKhachHang);

        mnuVeTau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnuVeTau.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\train-ticket.png")); // NOI18N
        mnuVeTau.setText("Vé tàu");
        mnuVeTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVeTauActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuVeTau);
        mnQuanLy.add(jSeparator5);

        mnuNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnuNhanVien.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\User group.png")); // NOI18N
        mnuNhanVien.setText("Nhân viên");
        mnuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNhanVienActionPerformed(evt);
            }
        });
        mnQuanLy.add(mnuNhanVien);

        menuBar.add(mnQuanLy);

        mnThongKe.setBackground(new java.awt.Color(214, 221, 255));
        mnThongKe.setForeground(new java.awt.Color(51, 0, 153));
        mnThongKe.setText("Thống kê");

        mnuDonahThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mnuDonahThu.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Bar chart.png")); // NOI18N
        mnuDonahThu.setText("Thống kê doanh thu");
        mnuDonahThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDonahThuActionPerformed(evt);
            }
        });
        mnThongKe.add(mnuDonahThu);

        menuBar.add(mnThongKe);

        mnHoTro.setBackground(new java.awt.Color(214, 221, 255));
        mnHoTro.setForeground(new java.awt.Color(51, 0, 153));
        mnHoTro.setText("Hỗ trợ");

        mnuCauHoi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        mnuCauHoi.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\customer-service.png")); // NOI18N
        mnuCauHoi.setText("Giải đáp câu hỏi");
        mnHoTro.add(mnuCauHoi);
        mnHoTro.add(jSeparator6);

        mnuGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuGioiThieu.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\letter.png")); // NOI18N
        mnuGioiThieu.setText("Giới thiệu");
        mnuGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGioiThieuActionPerformed(evt);
            }
        });
        mnHoTro.add(mnuGioiThieu);

        mnuHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuHuongDan.setIcon(new javax.swing.ImageIcon("D:\\PRO230 - UDPM - Java\\CodeJava\\DuAnTotNghiep\\TrainSys\\src\\main\\java\\trainsys\\icon\\Globe.png")); // NOI18N
        mnuHuongDan.setText("Hướng dẫn sử dụng");
        mnHoTro.add(mnuHuongDan);

        menuBar.add(mnHoTro);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        toolBar.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblThongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongtinMouseClicked
        
    }//GEN-LAST:event_lblThongtinMouseClicked

    private void btnChuyenTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenTauActionPerformed
        // TODO add your handling code here:
        openChuyenDi();
    }//GEN-LAST:event_btnChuyenTauActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void mnuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNhanVienActionPerformed
        // TODO add your handling code here:
        this.openNhanVien();
    }//GEN-LAST:event_mnuNhanVienActionPerformed

    private void mnuGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGioiThieuActionPerformed
        // TODO add your handling code here:
        this.moGioiThieu();
    }//GEN-LAST:event_mnuGioiThieuActionPerformed

    private void btnTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTauActionPerformed
        // TODO add your handling code here:
        this.openTau();
    }//GEN-LAST:event_btnTauActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        this.openKhachHang();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnVeTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeTauActionPerformed
        // TODO add your handling code here:
        this.openVeTau();
    }//GEN-LAST:event_btnVeTauActionPerformed

    private void mnuTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTauActionPerformed
        // TODO add your handling code here:
        this.openTau();
    }//GEN-LAST:event_mnuTauActionPerformed

    private void mnuChuyenDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChuyenDiActionPerformed
        // TODO add your handling code here:
        this.openChuyenDi();
    }//GEN-LAST:event_mnuChuyenDiActionPerformed

    private void mnuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKhachHangActionPerformed
        // TODO add your handling code here:
        this.openKhachHang();
    }//GEN-LAST:event_mnuKhachHangActionPerformed

    private void mnuVeTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVeTauActionPerformed
        // TODO add your handling code here:
        this.openVeTau();
    }//GEN-LAST:event_mnuVeTauActionPerformed

    private void mniDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMKActionPerformed
        // TODO add your handling code here:
        this.openDoiMatKhau();
    }//GEN-LAST:event_mniDoiMKActionPerformed

    private void mnuDonahThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDonahThuActionPerformed
        this.openDoanhThu(1);
    }//GEN-LAST:event_mnuDonahThuActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.dangXuat();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        this.ketThuc();
    }//GEN-LAST:event_mniKetThucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainSysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainSysJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhNen;
    private javax.swing.JButton btnChuyenDi;
    private javax.swing.JButton btnChuyenTau;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLichTrinh;
    private javax.swing.JButton btnTau;
    private javax.swing.JButton btnVeTau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblThongtin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenu mnHoTro;
    private javax.swing.JMenu mnQuanLy;
    private javax.swing.JMenu mnThongKe;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDoiMK;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mnuCauHoi;
    private javax.swing.JMenuItem mnuChuyenDi;
    private javax.swing.JMenuItem mnuDonahThu;
    private javax.swing.JMenuItem mnuGioiThieu;
    private javax.swing.JMenuItem mnuHuongDan;
    private javax.swing.JMenuItem mnuKhachHang;
    private javax.swing.JMenuItem mnuNhanVien;
    private javax.swing.JMenuItem mnuTau;
    private javax.swing.JMenuItem mnuVeTau;
    private javax.swing.JPanel statusBar;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    private void init() {
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);
        this.startDongHo();
        setLocationRelativeTo(null);
    }

    private void dangXuat() {
        Auth.clear();
        new DangNhapJDialog(this, true).setVisible(true);
    }
    
    private void ketThuc() {
        if(MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")){
            System.exit(0);
        }
    }
    
    void startDongHo() {
        SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
        new Timer(1000, (ActionEvent e) -> {
            lblDongHo.setText(formater.format(new Date()));
        }).start();
    }

    void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openTau() {
        if (Auth.isLogin()) {
            new TauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openChuyenDi() {
        if (Auth.isLogin()) {
            new ChuyenDiJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openVeTau() {
        if (Auth.isLogin()) {
            new VeJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    void openKhachHang() {
        if (Auth.isLogin()) {
            new KhachHangJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }

    private void moGioiThieu() {
        new GioiThieuJDialog(this, true).setVisible(true);
    }
    
    void openDoanhThu(int index) {
        if(Auth.isLogin()){
            if(index == 1 && !Auth.isManager()){
                MsgBox.alert(this, "Bạn không có quyền xem thông tin doanh thu");
                return;
            }
            ThongKeJDialog tkwin = new ThongKeJDialog(this, true);
            tkwin.selectTab(index);
            tkwin.setVisible(true);
        }
        else{
            MsgBox.alert(this, "Vui lòng đăng nhập!");
        }
    }
    
}
